version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Building the Lambda function..."
      - zip -g deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Uploading the Lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://deployment_package.zip
      - echo "DONE!!!"

